#!/usr/bin/env python3

# Very simple script for retrieving a list of open buffers

import os
import sys

import neovim


def main():
    socket_path = sys.argv[1]

    nvim = neovim.attach('socket', path=socket_path)

    pwd = os.getcwd()
    for buf in nvim.buffers:
        if buf.name.startswith(pwd):
            print(buf.name[len(pwd) + 1:])
        elif buf.name.startswith('term://'):
            continue
        else:
            print(buf.name)


if __name__ == "__main__":
    main()






















